### PR TITLE
add ghcr.io

### PR DESCRIPTION
**Pull request by ksurl**
Add an image in ghcr.io registry

## PREREQUISITES  
* create github personal access token with permissions for read/write packages as seen [here](https://docs.github.com/en/packages/guides/migrating-to-github-container-registry-for-docker-images)
* add the token as a secret in this repo named GITHUB_PASSWORD
* go to github profile settings and enable enhanced support for github containers

## POST MERGE  
* after first build has been published, package needs to be made public (defaults to private)

### CODE REVIEW

**Comment by Trane9991** [comment]
Hey @ksurl , thanks for the PR.
Unfortunately, I do not have access to repository settings to create an access token.
So only @mcuadros  can configure this to work.

**Comment by ksurl** [comment]
looks like it failed to publish the package in the workflow. may need to check the token permissions

**Comment by ksurl** [comment]
any update?

**Comment by maietta** [comment]
> any update?

Sorry about the late reply, but I just got here a couple days ago. Let me explain:

I've added a workflow in my version of Ofelia called Chronos. See https://github.com/mcuadros/ofelia/pull/137 for an explanation of what's I've done and why. Due to the fact that a pull request for a badly needed fix has now gone on for 30 days or more as of this writing, I felt the need to take that fixed version from the person who has contributed fixes, and made it into a new project called Chronos at https://github.com/PremoWeb/chronos.

The Chronos version has a few fixes, but still behind I think on some improvements to Ofelia. I've added a workflow to deploy a docker image to Github's Container Registry. You can get the image from ghcr.io/PremoWeb/Chronos:latest.

If this is helpful to you, great! If not, others may benefit. I just want to make sure you are aware.

**Pull request merged**
